apiVersion: v1
kind: Service
metadata:
    name: $NS-2048-service
    namespace: $NS
    labels:
        app: $NS-2048
spec:
    ports:
     - protocol: "TCP"
       port: 80
       targetPort: 80
    selector:
        app: $NS-2048
    type: LoadBalancer
    loadBalancerIP: ""
---
#EXAMPLE
apiVersion: v1
kind: Service
metadata:
    name: jothan-2048-service
    namespace: jothan
    labels:
        app: jothan-2048
spec:
    ports:
     - protocol: "TCP"
       port: 80
       targetPort: 80
    selector:
        app: jothan-2048
    type: LoadBalancer
    loadBalancerIP: ""
